### ISSUE TITLE
macOS Packaging MVP

### ISSUE THREAD

**Issue by marpaia** [kolide/launcher#77]
This is a master-task for the MVP of packaging on macOS.

## Blockers

- [x] The gRPC container is not running/exposed in production.
- [x] Determine what key is used to sign enrollment secrets for master and PRs.
- [x] Determine what key is used to sign enrollment secrets for prod.
- [x] Determine what key is used to sign macOS packages.
- [x] https://github.com/kolide/cloud/commit/fc0334d0c449d1d3ee1d3498404e83407fbed178 needs to be deployed to production

## TODO

- [x] Update the gRPC hostname to be `localhost:8082` when the app is being ran on `http://localhost:5000`
- [x] Add the `--grpc_insecure` flag to the launcher's LaunchDaemon template when the app is being ran on `http://localhost:5000`
- [x] Update the gRPC hostname to be `master-grpc.cloud.kolide.net:443` when the app is being ran on `https://master.cloud.kolide.net`
- [x] Update the gRPC hostname to be `123.cloud.kolide.net:443` when the app is being ran on `https://123.cloud.kolide.net`
- [x] Write a subcommand to produce production packages given the production key
- [x] Update the gRPC hostname to be `launcher.kolide.com:443` when the app is being ran on `https://kolide.com`
- [x] Add the ability to sign mac packages to `package-builder`
- [x] Shard launcher root directories by gRPC server hostname

## Acceptance Tests

- [x] Use the setup guide to download and install a macOS package from the app running locally and verify that the host connects to the instance.
- [x] Use the setup guide to download and install a macOS package from the app running from a PR deployment and verify that the host connects to the instance.
- [x] Use the setup guide to download and install a macOS package from the app running on the master deployment and verify that the host connects to the instance.
- [x] Use the setup guide to download and install a macOS package from the app running on the production deployment and verify that the host connects to the instance.
