### ISSUE TITLE
autoupdate issues for MVP

### ISSUE THREAD

**Issue by groob** [kolide/launcher#85]
The autoupdate feature for the launcher/osquery binaries has been added the the launcher, but several important items remain:

# launcher/updater code:
- [x] complete https://github.com/kolide/launcher/pull/69, which adds tooling for updating the mirror with osqueryd versions based on the osquery.io releases
- [x] also add tooling which creates a tar.gz file for launcher and tags the release as stable/beta/specific-version, similar to #69 
- [x] close https://github.com/kolide/launcher/issues/59, related to the two tasks above
- [x] troubleshoot and resolve https://github.com/kolide/launcher/issues/66, possibly related to lack of delegate target support in the autoupdate package. 
- [x] add delegation support to `launcher/autoupdate` and unpin the updater dependency (depends on #66 getting fixed) https://github.com/kolide/launcher/blob/ae4e571371bec019b44521ff533386cc9b655f84/glide.yaml#L13
- [x] Add delegation support to Launcher
- [x] Update package-builder to include initial TUF metadata and Notary URL

# infrastructure

The notary service requires two mysql databases (server and signer) as well as the go dependencies. So far, I stood up all the required infrastructure, but using the bundled example keys. 
The services and databases need to be re-launched with production level keys. 

- [x] generate CA and client certificates for the notary server & signer. 

These are the current configs that need to be replaced:
server-config:
```
	"trust_service": {
		"type": "remote",
		"hostname": "notarysigner",
		"port": "7899",
		"tls_ca_file": "/go/src/github.com/docker/notary/fixtures/root-ca.crt",
		"key_algorithm": "ecdsa",
		"tls_client_cert": "/go/src/github.com/docker/notary/fixtures/notary-server.crt",
		"tls_client_key": "/go/src/github.com/docker/notary/fixtures/notary-server.key"
	},
```

signer-config:
```
	"server": {
		"grpc_addr": "0.0.0.0:7899",
		"tls_cert_file": "/go/src/github.com/docker/notary/fixtures/notary-signer.crt",
		"tls_key_file": "/go/src/github.com/docker/notary/fixtures/notary-signer.key",
		"client_ca_file": "/go/src/github.com/docker/notary/fixtures/notary-server.crt"
	},
```

The important part is understanding the relationship between the two services so that keys are unique for server/signer. Another important and non-trivial issue is limiting access to the root keys and securely storing them  -- a company wide 1password vault is not appropriate. 

- [x]  re-launch the mirror and dbs from scratch once unique keys are added. (relatively minor, but good hygiene). 

- [x] add DNS entries for: 
```
35.196.246.167 notary.kolide.co
35.196.246.167 notary.kolide.com
```
# Documentation

- [x] write up a workflow for publishing new binary releases.
Document a workflow for signing and publishing new launcher & osquery updates, such that more than one person on the team can create releases and launcher and osquery versions can be published to the mirror independently. 

# Testing

I tested that the launcher and osquery versions are both replaced/restarted when a new version of the binary is published to the website. It appears to work well, but there are still many possible edge cases that should be tested extensively, before we enable auto-update for a customer in production. 
Some possible issues: 
  - specifying a beta/other channel
  - what happens if you accidentally publish the metadata before updates are available on the mirror
  - validate that if the binary release is broken, the launcher/osquery can auto-recover with the previous version, instead of failing to start forever.
  - the ability to rotate TUF keys in production without affecting the customer
